{% set version = "1.0.5" %}


package:
  name: h2mm-c
  version: {{ version }}

source:
  url: https://github.com/harripd/H2MMpythonlib/archive/{{ version }}.tar.gz
  sha256: 949ab32a3255d286fbb09b2bb9918bac21d4fd6c0cb4216dfc264bf82fa827ce

build:
  skip: true   # [py<37]
  script_env: 
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - setuptools >=64
    - setuptools-scm >=6.0
    - wheel
    - cython
    - ipython
    - numpy
    - pip
  run:
    - python
    - ipython
    - importlib-metadata
    - numpy

test:
  imports:
    - H2MM_C
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/harripd/H2MMpytonlib
  summary: C level implementation of H2MM algorithm by Pirchi. 2016
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - harripd
