{% set version = "2.1.2" %}


package:
  name: h2mm-c
  version: {{ version }}

source:
  url: https://github.com/harripd/H2MMpythonlib/archive/{{ version }}.tar.gz
  sha256: c0c3a2178a6747e35465195f3b75c6737166a20e9170b92027149c181a93806f

build:
  skip: true  # [py<37]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - setuptools >=64
    - setuptools-scm >=8.0
    - wheel
    - cython
    - numpy
    - pip
    - ipython
  run:
    - python
    - importlib-metadata
    - numpy
    - ipython

test:
  imports:
    - H2MM_C
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/harripd/H2MMpytonlib
  summary: C level implementation of H2MM algorithm by Pirchi. 2016
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - harripd
